# Load config files

# Program variables
source = ~/.config/hypr/programs.conf

# Input configuration
source = ~/.config/hypr/input.conf

# Auto-start processes
source = ~/.config/hypr/autostart.conf

# Environment variables
source = ~/.config/hypr/environment_var.conf

# Keybindings
source = ~/.config/hypr/keybindings.conf

# Looks and feel
source = ~/.config/hypr/look_and_feel.conf

# Monitor configurations
source = ~/.config/hypr/monitors.conf

# Permissions configurations
source = ~/.config/hypr/permissions.conf

# Window rules
source = ~/.config/hypr/window_rules.conf
