####################
###   PROGRAMS   ###
####################

# See https://wiki.hypr.land/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = thunar
$browser = zen-browser
$menu = rofi -show run
